corpus_manager/urls.py
# Necessary imports
from django.urls import path
from . import views

"""
URL patterns for the Corpus Manager application.

This module defines the URL patterns for the different views in the Corpus Manager application.
Each URL pattern is associated with a specific view function.

URL Patterns:
- "" (empty string): The index view.
- "home/": The home view.
- "add/": The add view.
- "deletion/": The deletion view.
- "home/delete/<int:id>/<int:choice>/": The delete view.
- "home/update/<int:id>/<int:choice>/": The update view.
- "upload/": The upload view.
- "api/parallel-texts/": The ParallelTextListCreate view.
- "signup/": The register view.
- "login/": The signin view.
- "logout/": The signout view.
"""

urlpatterns = [
    path("", views.index, name="index"),
    path("home/", views.home, name="home"),
    path("insert/", views.insert, name="insert"),
    path('deletion/', views.deletion, name='deletion'),
    path('delete-multiple/', views.delete_multiple, name='delete-multiple'),
    path('ignore-multiple/', views.ignore_multiple, name='ignore-multiple'),
    path('home/delete/<int:id>/<int:choice>/', views.delete, name='delete'),
    path('home/update/<int:id>/<int:choice>/', views.update, name='update'),
    path('upload/', views.upload, name='upload'),
    path('api/parallel-texts/', views.ParallelTextListCreate.as_view(), name='parallel-text-list-create'),
    path('signup/', views.register, name='signup'),
    path('login/', views.signin, name='login'),
    path('logout/', views.signout, name='logout')
]

parallel_corpus_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('corpus_manager.urls')),
]

corpus_manager/models.py
# Necessary imports
from django.db import models

class ParallelText(models.Model):
    """
    Model representing parallel texts in different languages (currently three languages).
    """
    en_text = models.TextField()
    hi_text = models.TextField(null=True, blank=True)
    mn_text = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    verify_en_mn = models.IntegerField(choices=[(i, str(i)) for i in range(1, 6)],null=True, blank=True)
    verify_hi_mn = models.IntegerField(choices=[(i, str(i)) for i in range(1, 6)],null=True, blank=True)
    verify_en_hi = models.IntegerField(choices=[(i, str(i)) for i in range(1, 6)],null=True, blank=True)
    requested = models.BooleanField(default=False)
    

class DeletionRequest(models.Model):
    """
    Model representing deletion requests for parallel texts.
    """
    parallel_text = models.ForeignKey(ParallelText, on_delete=models.CASCADE)
    requested_by = models.CharField(max_length=255)
    requested_at = models.DateTimeField(auto_now_add=True)

corpus_manager/forms.py
# Necessary imports
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import ParallelText

class CustomSignupForm(UserCreationForm):
    """
    A custom form for user signup.

    Inherits from UserCreationForm and adds additional fields for email and role.
    """

    # Additional field for email
    email = forms.EmailField()

    # Choices for the role field
    role_choices = [
        ('Data Manager', 'Data Manager'),
        ('Translator', 'Translator'),
        ('Validator', 'Validator'),
    ]

    # Field for selecting the role
    role = forms.ChoiceField(choices=role_choices)

    class Meta:
        # Specify the model to be used for the form
        model = User
        
        # Specify the fields to be included in the form
        fields = ["username", "email", "password1", "password2"]

class ParallelTextForm(forms.ModelForm):
    """
    A form for creating and updating parallel texts.

    Inherits from ModelForm and specifies the model and fields to be used.
    """

    class Meta:
        # Specify the model to be used for the form
        model = ParallelText

        # Specify the fields to be included in the form
        fields = ['en_text', 'hi_text', 'mn_text', 'verify_en_mn', 'verify_hi_mn', 'verify_en_hi']

class FilterForm(forms.Form):
    """
    A form for filtering parallel texts.

    Provides choices for source and target languages.
    """

    # Choices for source and target languages
    choices = [
        ('en', 'English'),
        ('hi', 'Hindi'),
        ('mn', 'Manipuri')
    ]
    # Field for selecting the source language
    source = forms.ChoiceField(choices=choices)
    # Field for selecting the target language
    target = forms.ChoiceField(choices=choices)

corpus_manager/views.py
# Necessary imports
from rest_framework import generics
from .models import ParallelText, DeletionRequest
from .serializers import ParallelTextSerializer
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CustomSignupForm, ParallelTextForm, FilterForm
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required

# Define the index view
def index(request):
    return render(request, "index.html")

# Define the home view
@login_required(login_url="login")
def home(request):
    # Get all parallel texts
    parallel_texts = ParallelText.objects.all()
   
    # Get the choice from the session; gives None if doesn't exist
    choice = request.session.get('choice')

    if request.method == "GET":
        if 'search_query' in request.GET:
            # Get the search query from the request
            search_query = request.GET.get("search_query")
            
            # Filter the parallel texts based on the search query
            parallel_texts = ParallelText.objects.filter(en_text__icontains=search_query)

            if "choice" in request.GET:
                choice = int(request.GET.get("choice"))
                return render(request,"basetv.html", {"parallel_texts": parallel_texts, "choice": choice})

    if request.method == "POST":
        if 'go' in request.POST:
            # Create a form instance and populate it with data from the request
            form = FilterForm(request.POST)
            if form.is_valid():
                # Get the source and target languages from the form
                source = form.cleaned_data.get("source")
                target = form.cleaned_data.get("target")

                # Check the language pair and render the appropriate template
                if set([source, target]) == set(["en", "hi"]):
                    return render(request,"basetv.html", {"parallel_texts": parallel_texts, "choice": 1})
                elif set([source, target]) == set(["en", "mn"]):
                    return render(request,"basetv.html", {"parallel_texts": parallel_texts, "choice": 2})
                elif set([source, target]) == set(["hi", "mn"]):
                    return render(request,"basetv.html", {"parallel_texts": parallel_texts, "choice": 3})
                else:
                    messages.info(request, "Invalid language pair. Please select a valid language pair.")
    else:
        form = FilterForm()

    if choice:
        # Remove the choice from the session
        del request.session['choice']
        if choice != 0:
            return render(request, "basetv.html", {"parallel_texts": parallel_texts, "choice": choice})

    return render(request, "base.html", {"parallel_texts": parallel_texts, "form": form, "choice": 0})

# Define the add ParallelText view
@login_required(login_url="login")
def insert(request):
    if request.method == "POST":
        form = ParallelTextForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("home")
    else:
        form = ParallelTextForm()
    return render(request, "add.html", {"form": form})

# Define the delete ParallelText view
@login_required(login_url="login")
def delete(request, id, choice):
    # Get the parallel text object with the given id
    parallel_texts = ParallelText.objects.get(id=id)
    
    # Check if the user is a Data Manager
    if request.user.groups.filter(name="Data Manager").exists():
        # Delete the parallel text object
        parallel_texts.delete()
        
        # Redirect based on the choice
        if choice == 4:
            return redirect('deletion')
        return redirect('home')
    else:
        # Set the requested flag to True
        parallel_texts.requested = True
        parallel_texts.save()

        # Create a deletion request
        deletion_request = DeletionRequest(parallel_text=parallel_texts, requested_by=request.user.username)
        deletion_request.save()
                
        # Set the choice in the session
        request.session['choice'] = choice
        
        return redirect('home')

# Define the delete_multiple view
@login_required(login_url="login")
def delete_multiple(request):
    if request.method == 'POST':
        # Get the list of items to delete from the request
        items_to_delete = request.POST.getlist('row-checkbox')
        
        # Delete the selected items from the ParallelText model
        ParallelText.objects.filter(pk__in=items_to_delete).delete()
    
    # Redirect to the deletion page
    return redirect('deletion')

# Define the ignore_multiple view
def ignore_multiple(request):
    if request.method == 'POST':
        # Get the list of items to ignore from the request
        items_to_ignore = request.POST.getlist('row-checkbox')
        
        # Set the requested flag to False for the selected items
        ParallelText.objects.filter(pk__in=items_to_ignore).update(requested=False)

        # Delete the selected items from the DeletionRequest model
        DeletionRequest.objects.filter(parallel_text__in=items_to_ignore).delete()
        
    # Redirect to the deletion requests page
    return redirect('deletion')

# Define the deletion request view
def deletion(request):
    # Get all deletion requests
    deletion_requests = DeletionRequest.objects.all()
    # Render the deletion.html template with deletion requests
    return render(request, "deletion.html", {"deletion_requests": deletion_requests})

# Define the update ParallelText view
@login_required(login_url="login")
def update(request, id, choice):
    # Get the parallel text object with the given id
    parallel_texts = get_object_or_404(ParallelText, id=id)
    
    # Create a form instance and populate it with data from the request
    form = ParallelTextForm(request.POST or None, instance=parallel_texts)
    
    if form.is_valid():
        # Save the form
        form.save()
        
        # Set the choice in the session
        request.session['choice'] = choice
        
        return redirect("home")
    
    return render(request, 'update.html', {'form': form, 'choice': choice})

# Define the upload data view
@login_required(login_url="login")
def upload(request):
    return render(request, 'upload.html')

# Define the ParallelTextListCreate view
class ParallelTextListCreate(generics.ListCreateAPIView):
    # Get all parallel texts
    queryset = ParallelText.objects.all()
    
    # Use the ParallelTextSerializer for serialization
    serializer_class = ParallelTextSerializer

# Define the register user view
def register(request):
    if request.user.is_authenticated:
        return redirect("home")
    else:
        if request.method == "POST":
            form = CustomSignupForm(request.POST)
            if form.is_valid():
                # Get the role from the form
                role = form.cleaned_data.get("role")
                
                # Save the user form
                user = form.save()
                
                # Get the group based on the role
                group = Group.objects.get(name=role)
                
                # Add the user to the group
                user.groups.add(group)
                
                # Login the user
                login(request, user)
                
                return redirect("home")
        else:
            form = CustomSignupForm()

        return render(request, "signup.html", {"form": form})

# Define the user signin view
def signin(request):
    if request.user.is_authenticated:
        return redirect("home")
    else:
        if request.method == "POST":
            form = AuthenticationForm(data=request.POST)
            if form.is_valid():
                # Get the username and password from the form
                username = form.cleaned_data.get("username")
                password = form.cleaned_data.get("password")
                
                # Authenticate the user
                user = authenticate(request, username=username, password=password)
                if user:
                    # Login the user
                    login(request, user)
                    return redirect("home")
                else:
                    messages.info(request, "Username or password is incorrect")
        else:
            form = AuthenticationForm()

        return render(request, "login.html", {"form": form})

# Define the user signout view
def signout(request):
    # Logout the user
    logout(request)
    # Redirect to the index page
    return redirect("index")

corpus_manager/templates/add.html
{% load static %}
<!DOCTYPE html >
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'add.css' %}">
    <title>Add</title>
</head>

<body>
    <div class="container1">
        <h1>Add Corpus</h1>
        <form action="" method="post">
            {% csrf_token %}

            <label for="id_en_text">English Text:</label>
            <input type="text" id="id_en_text" name="en_text" value="{{ form.en_text.value|default_if_none:'' }}"><br>

            <label for="id_hi_text">Hindi Text:</label>
            <input type="text" id="id_hi_text" name="hi_text" value="{{ form.hi_text.value|default_if_none:'' }}"><br>

            <label for="id_mn_text">Manipuri Text:</label>
            <input type="text" id="id_mn_text" name="mn_text" value="{{ form.mn_text.value|default_if_none:'' }}"><br>

            <label for="id_verify_en_mn">Verify_en_mn:</label>
            <input type="number" min="1" max="5" id="id_verify_en_mn" name="verify_en_mn" value="{{ form.verify_en_mn.value }}"><br>
            
            <label for="id_verify_hi_mn">Verify_hi_mn:</label>
            <input type="number" min="1" max="5" id="id_verify_hi_mn" name="verify_hi_mn" value="{{ form.verify_hi_mn.value }}"><br>
            
            <label for="id_verify_en_hi">Verify_en_hi:</label>
            <input type="number" min="1" max="5" id="id_verify_en_hi" name="verify_en_hi" value="{{ form.verify_en_hi.value }}"><br>
                
            <button type="submit" id="new1">Add</button>
        </form>
    </div>
</body>

</html>

corpus_manager/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    <title>Home</title>
</head>
{% load auth_extras %}

<body>
    <div class="container">
        <p>Hello! {{request.user}}
        <a href="{% url 'logout' %}"><button id="new">logout</button></a>
        </p>
        {% if request.user|has_group:"Data Manager" %}
        <a href="{% url 'deletion' %}"><button id="new">deletion requests</button></a>

        <h1>Parallel Corpus</h1>
            <form method="get">
                <input type="text" placeholder="Search.." name="search_query">
                <button type="submit">Search</button>
            </form>
            <table id="customers" border="1">
                <thead>
                    <th>English Text</th>
                    <th>Hindi Text</th>
                    <th>Manipuri Text</th>
                    <th>Created at</th>
                    <th>Verify_en_mn</th>
                    <th>Verify_hi_mn</th>
                    <th>Verify_en_hi</th>
                    <th colspan="2" id="mid">Action</th>
                </thead>
                {% for parallel_text in parallel_texts %}
                <tr>
                    <td>{{ parallel_text.en_text }}</td>
                    <td>{{ parallel_text.hi_text }}</td>
                    <td>{{ parallel_text.mn_text }}</td>
                    <td>{{ parallel_text.created_at }}</td>
                    <td>{{ parallel_text.verify_en_mn }}</td>
                    <td>{{ parallel_text.verify_hi_mn }}</td>
                    <td>{{ parallel_text.verify_en_hi }}</td>
                    <td>
                        <a href="update/{{parallel_text.id}}/{{choice}}"><button id="up">Update</button></a>
                    </td>
                    <td>
                        <a href="delete/{{parallel_text.id}}/{{choice}}"><button id="del">Delete</button></a>
                    </td>
                </tr>
                {% endfor %}
            </table>
            <br><br>
            
            <a href="{% url 'insert' %}"><button id="new3">Add</button></a>
            <a href="{% url 'upload' %}"><button id="new3">Upload/Download</button></a>
        {% else %}
        <h1>Parallel Corpus</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" name="go">Go</button>
            </form>
        {% endif %}
    </div>
    {{ redirect_to_login_immediately }}
</body>

</html>

corpus_manager/templates/basetv.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'basetv.css' %}">
    <title>Home</title>
</head>
{% load auth_extras %}

<body>
    <div class="container">
        <p>Hello! {{request.user}}
        <a href="{% url 'logout' %}"><button id="new">logout</button></a>
        </p>

        <h1>Parallel Corpus</h1>
            <form method="get">
                <input type="text" placeholder="Search.." name="search_query">
                <input type="text" value={{choice}} name="choice" hidden>
                <button type="submit">Search</button>
            </form>

        {% if request.user|has_group:"Translator" %}
        {% if choice == 1 %}
            <table id="customers" border="1">
                <thead>
                    <th>English Text</th>
                    <th>Hindi Text</th>
                    <th>Created at</th>
                    <th>Verification level</th>
                    <th colspan="2" id="mid">Action</th>
                </thead>
                {% for parallel_text in parallel_texts %}
                {% if parallel_text.en_text and not parallel_text.hi_text or not parallel_text.en_text and parallel_text.hi_text %}
                <tr>
                    <td>{{parallel_text.en_text}}</td>
                    <td>{{parallel_text.hi_text}}</td>
                    <td>{{parallel_text.created_at}}</td>
                    <td>{{parallel_text.verify_en_hi}}</td>
                    <td>
                        <a href="update/{{parallel_text.id}}/{{choice}}"><button id="up">Update</button></a>
                    </td>
                    <td>
                        {% if parallel_text.requested %}
                        <a href=""><button id="del" disabled>Delete</button></a>
                        {% else %}
                        <a href="delete/{{parallel_text.id}}/{{choice}}"><button id="del">Delete</button></a>
                        {% endif %}
                    </td>
                </tr>
                {% endif %}
                {% endfor %}
            </table>

        {% elif choice == 2 %}
            <table id="customers" border="1">
                <thead>
                    <th>English Text</th>
                    <th>Manipuri Text</th>
                    <th>Created at</th>
                    <th>Verification level</th>
                    <th colspan="2" id="mid">Action</th>
                </thead>
                {% for parallel_text in parallel_texts %}
                {% if parallel_text.en_text and not parallel_text.mn_text or not parallel_text.en_text and parallel_text.mn_text %}
                <tr>
                    <td>{{parallel_text.en_text}}</td>
                    <td>{{parallel_text.mn_text}}</td>
                    <td>{{parallel_text.created_at}}</td>
                    <td>{{parallel_text.verify_en_mn}}</td>
                    <td>
                        <a href="update/{{parallel_text.id}}/{{choice}}"><button id="up">Update</button></a>
                    </td>
                    <td>
                        {% if parallel_text.requested %}
                        <a href=""><button id="del" disabled>Delete</button></a>
                        {% else %}
                        <a href="delete/{{parallel_text.id}}/{{choice}}"><button id="del">Delete</button></a>
                        {% endif %}
                    </td>
                </tr>
                {% endif %}
                {% endfor %}
            </table>

        {% elif choice == 3 %}
            <table id="customers" border="1">
                <thead>
                    <th>Hindi Text</th>
                    <th>Manipuri Text</th>
                    <th>Created at</th>
                    <th>Verification level</th>
                    <th colspan="2" id="mid">Action</th>
                </thead>
                {% for parallel_text in parallel_texts %}
                {% if parallel_text.mn_text and not parallel_text.hi_text or not parallel_text.mn_text and parallel_text.hi_text %}
                <tr>
                    <td>{{parallel_text.hi_text}}</td>
                    <td>{{parallel_text.mn_text}}</td>
                    <td>{{parallel_text.created_at}}</td>
                    <td>{{parallel_text.verify_hi_mn}}</td>
                    <td>
                        <a href="update/{{parallel_text.id}}/{{choice}}"><button id="up">Update</button></a>
                    </td>
                    <td>
                        {% if parallel_text.requested %}
                        <a href=""><button id="del" disabled>Delete</button></a>
                        {% else %}
                        <a href="delete/{{parallel_text.id}}/{{choice}}"><button id="del">Delete</button></a>
                        {% endif %}
                    </td>
                </tr>
                {% endif %}
                {% endfor %}
            </table>

        {% endif %}

        {% elif request.user|has_group:"Validator" %}
        {% if choice == 1 %}
            <table id="customers" border="1">
                <thead>
                    <th>English Text</th>
                    <th>Hindi Text</th>
                    <th>Created at</th>
                    <th>Verification level</th>
                    <th colspan="2" id="mid">Action</th>
                </thead>
                {% for parallel_text in parallel_texts %}
                {% if parallel_text.en_text != '' and parallel_text.hi_text != '' %}
                <tr>
                    <td>{{parallel_text.en_text}}</td>
                    <td>{{parallel_text.hi_text}}</td>
                    <td>{{parallel_text.created_at}}</td>
                    <td>{{parallel_text.verify_en_hi}}</td>
                    <td>
                        <a href="update/{{parallel_text.id}}/{{choice}}"><button id="up">Update</button></a>
                    </td>
                    <td>
                        {% if parallel_text.requested %}
                        <a href=""><button id="del" disabled>Delete</button></a>
                        {% else %}
                        <a href="delete/{{parallel_text.id}}/{{choice}}"><button id="del">Delete</button></a>
                        {% endif %}
                    </td>
                </tr>
                {% endif %}
                {% endfor %}
            </table>

        {% elif choice == 2 %}
            <table id="customers" border="1">
                <thead>
                    <th>English Text</th>
                    <th>Manipuri Text</th>
                    <th>Created at</th>
                    <th>Verification level</th>
                    <th colspan="2" id="mid">Action</th>
                </thead>
                {% for parallel_text in parallel_texts %}
                {% if parallel_text.en_text != '' and parallel_text.mn_text != '' %}
                <tr>
                    <td>{{parallel_text.en_text}}</td>
                    <td>{{parallel_text.mn_text}}</td>
                    <td>{{parallel_text.created_at}}</td>
                    <td>{{parallel_text.verify_en_mn}}</td>
                    <td>
                        <a href="update/{{parallel_text.id}}/{{choice}}"><button id="up">Update</button></a>
                    </td>
                    <td>
                        {% if parallel_text.requested %}
                        <a href=""><button id="del" disabled>Delete</button></a>
                        {% else %}
                        <a href="delete/{{parallel_text.id}}/{{choice}}"><button id="del">Delete</button></a>
                        {% endif %}
                    </td>
                </tr>
                {% endif %}
                {% endfor %}
            </table>

        {% elif choice == 3 %}
            <table id="customers" border="1">
                <thead>
                    <th>Hindi Text</th>
                    <th>Manipuri Text</th>
                    <th>Created at</th>
                    <th>Verification level</th>
                    <th colspan="2" id="mid">Action</th>
                </thead>
                {% for parallel_text in parallel_texts %}
                {% if parallel_text.mn_text != '' and parallel_text.hi_text != '' %}
                <tr>
                    <td>{{parallel_text.hi_text}}</td>
                    <td>{{parallel_text.mn_text}}</td>
                    <td>{{parallel_text.created_at}}</td>
                    <td>{{parallel_text.verify_hi_mn}}</td>
                    <td>
                        <a href="update/{{parallel_text.id}}/{{choice}}"><button id="up">Update</button></a>
                    </td>
                    <td>
                        {% if parallel_text.requested %}
                        <a href=""><button id="del" disabled>Delete</button></a>
                        {% else %}
                        <a href="delete/{{parallel_text.id}}/{{choice}}"><button id="del">Delete</button></a>
                        {% endif %}
                    </td>
                </tr>
                {% endif %}
                {% endfor %}
            </table>

        {% endif %}

        {% endif %}

        <a href="{% url 'home' %}"><button id="new3">Select languages</button></a>
        {{ redirect_to_login_immediately }}

    </div>
</body>

</html>

corpus_manager/templates/update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'update.css' %}">
    <title>Update</title>
</head>
{% load auth_extras %}

<body>
    <div class="container2">
        <h1>Update Corpus</h1>
        {% if choice == 0 %}
            <form action="" method="post">
                {% csrf_token %}

                <label for="id_en_text">English Text:</label>
                <input type="text" id="id_en_text" name="en_text" value="{{ form.en_text.value }}"><br>

                <label for="id_hi_text">Hindi Text:</label>
                <input type="text" id="id_hi_text" name="hi_text" value="{{ form.hi_text.value }}"><br>

                <label for="id_mn_text">Manipuri Text:</label>
                <input type="text" id="id_mn_text" name="mn_text" value="{{ form.mn_text.value }}"><br>

                <label for="id_verify_en_mn">Verify_en_mn:</label>
                <input type="number" min="1" max="5" id="id_verify_en_mn" name="verify_en_mn" value="{{ form.verify_en_mn.value }}"><br>
                
                <label for="id_verify_hi_mn">Verify_hi_mn:</label>
                <input type="number" min="1" max="5" id="id_verify_hi_mn" name="verify_hi_mn" value="{{ form.verify_hi_mn.value }}"><br>
                
                <label for="id_verify_en_hi">Verify_en_hi:</label>
                <input type="number" min="1" max="5" id="id_verify_en_hi" name="verify_en_hi" value="{{ form.verify_en_hi.value }}"><br>
                
                <button type="submit" id="new2">Update</button>
            </form>
        {% elif choice == 1 %}
            <form action="" method="post">
                {% csrf_token %}

                <label for="id_en_text">English Text:</label>
                <input type="text" id="id_en_text" name="en_text" value="{{ form.en_text.value }}"><br>

                <label for="id_hi_text">Hindi Text:</label>
                <input type="text" id="id_hi_text" name="hi_text" value="{{ form.hi_text.value }}"><br>

                <label for="id_verify_en_hi">Verify_en_hi:</label>
                <input type="number" min="1" max="5" id="id_verify_en_hi" name="verify_en_hi" value="{{ form.verify_en_hi.value }}"><br>

                <button type="submit" id="new2">Update</button>
            </form>

        {% elif choice == 2 %}
            <form action="" method="post">
                {% csrf_token %}

                <label for="id_en_text">English Text:</label>
                <input type="text" id="id_en_text" name="en_text" value="{{ form.en_text.value }}"><br>

                <label for="id_mn_text">Manipuri Text:</label>
                <input type="text" id="id_mn_text" name="mn_text" value="{{ form.mn_text.value }}"><br>

                <label for="id_verify_en_mn">Verify_en_mn:</label>
                <input type="number" min="1" max="5" id="id_verify_en_mn" name="verify_en_mn" value="{{ form.verify_en_mn.value }}"><br>

                <button type="submit" id="new2">Update</button>
            </form>

        {% elif choice == 3 %}
            <form action="" method="post">
                {% csrf_token %}

                <label for="id_hi_text">Hindi Text:</label>
                <input type="text" id="id_hi_text" name="hi_text" value="{{ form.hi_text.value }}"><br>

                <label for="id_mn_text">Manipuri Text:</label>
                <input type="text" id="id_mn_text" name="mn_text" value="{{ form.mn_text.value }}"><br>

                <label for="id_verify_hi_mn">Verify_hi_mn:</label>
                <input type="number" min="1" max="5" id="id_verify_hi_mn" name="verify_hi_mn" value="{{ form.verify_hi_mn.value }}"><br>

                <button type="submit" id="new2">Update</button>
            </form>

        {% endif %}
    </div>
</body>

</html>